#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "reactive-resume"
name = "Reactive-Resume"
description.en = "Resume builder that keeps your privacy in mind"
description.fr = "Un créateur de CV qui respecte votre vie privée"

version = "4.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://rxresu.me/"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/AmruthPillai/Reactive-Resume"
fund = "https://opencollective.com/reactive-resume"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/AmruthPillai/Reactive-Resume/archive/refs/tags/v4.4.0.tar.gz"
    sha256 = "e9caf6c34bf9ee21384b685aa22d1db1772a4931f129b81b95cc8e5035fdb475"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
